export declare enum ServerType {
    REALTIME_SYNCHRONIZER = "REALTIME_SYNCHRONIZER",
    SYNC_LOG_PROCESSOR = "SYNC_LOG_PROCESSOR",
    TRANS_DATA_ACCUMULATOR = "TRANS_DATA_ACCUMULATOR"
}
//# sourceMappingURL=ServerType.d.ts.map