import { IAirportDatabasePopulator } from './AirportDatabasePopulator';
import { IDdlObjectLinker } from './DdlObjectLinker';
import { IDdlObjectRetriever } from './DdlObjectRetriever';
import { IQueryEntityClassCreator } from './QueryEntityClassCreator';
import { IQueryObjectInitializer } from './QueryObjectInitializer';
export declare const AIR_DB_POPULATOR: import("@airport/di").DiToken<IAirportDatabasePopulator>;
export declare const DDL_OBJECT_LINKER: import("@airport/di").DiToken<IDdlObjectLinker>;
export declare const DDL_OBJECT_RETRIEVER: import("@airport/di").DiToken<IDdlObjectRetriever>;
export declare const QUERY_ENTITY_CLASS_CREATOR: import("@airport/di").DiToken<IQueryEntityClassCreator>;
export declare const QUERY_OBJECT_INITIALIZER: import("@airport/di").DiToken<IQueryObjectInitializer>;
