export declare enum ServerErrorType {
    DUPLICATE_INCOMING_DATABASE_KEYS_HAVE_NO_MATCHING_DATABASE = 0,
    DUPLICATE_INCOMING_DATABASE_KEYS_HAVE_INCORRECT_HASH = 1,
    INCOMING_DATABASE_HASH_DOES_NOT_MATCH = 2,
    INCOMING_DATABASE_KEY_APPEARS_MORE_THAN_ONCE_IN_THE_BATCH = 3,
    INCOMING_DATABASE_SYNC_LOG_KEY_APPEARS_MORE_THAN_ONCE_IN_A_REQUEST = 4,
    INCOMING_DATABASE_RECORD_WASNT_IN_DATABASES_TABLE = 5,
    INCOMING_REPOSITORY_REPOSITORY_ID_NOT_FOUND = 6,
    MULTIPLE_DUPLICATE_INCOMING_DATABASE_KEYS_HAVE_CORRECT_HASH = 7,
    SYNC_CLIENT_CONNECTED_TOO_SOON = 8
}
//# sourceMappingURL=ServerErrorType.d.ts.map