export type TmToAgtProtocolVersion = 0;

export enum MessageToTMContentType {
	REPOSITORY_TRANSACTION_BLOCK,
	SYNC_NOTIFICATION,
	// SYNC_ACK,
	ALIVE_ACK
}

export enum RepoTransBlockSyncOutcomeType {
	SYNC_FROM_TM_ALREADY_SYNCED,
	SYNC_FROM_TM_SUCCESSFUL,
	SYNC_FROM_TM_DENIED_DATABASE_NOT_FOUND,
	SYNC_FROM_TM_DENIED_REPOSITORY_NOT_FOUND,
	SYNC_FROM_TM_DENIED_NO_WRITE_PERMISSION,
	SYNC_TO_TM_SUCCESSFUL,
	SYNC_TO_TM_READY_FOR_PROCESSING,
	SYNC_TO_TM_NEEDS_SCHEMA_CHANGES,
	SYNC_TO_TM_NEEDS_ADDITIONAL_DATA,
	SYNC_TO_TM_NEEDS_DATA_UPGRADES
}

export enum MessageFromTMContentType {
	CONNECTION_REQUEST,
	SYNC_VERIFICATIONS,
	DATA_TRANSFER
}