export type TmToAgtProtocolVersion = 0;

export enum MessageToTMContentType {
	REPOSITORY_TRANSACTION_BLOCK,
	SYNC_NOTIFICATION,
	// SYNC_ACK,
	ALIVE_ACK
}

export enum RepoTransBlockSyncOutcomeType {
	BLOCK_IS_LOCAL,
	SYNC_TO_TM_SUCCESSFUL,
	SYNC_TO_TM_READY_FOR_PROCESSING,
	SYNC_TO_TM_NEEDS_SCHEMA_CHANGES,
	SYNC_TO_TM_NEEDS_ADDITIONAL_DATA,
	SYNC_TO_TM_INVALID_DATA,
	SYNC_TO_TM_NEEDS_DATA_UPGRADES
}

export enum SharingNodeRepoTransBlockSyncStatus {
	TM_STATUS_RTB_SYNCHRONIZING,
	// SYNCHRONIZED,
	TM_STATUS_REQUESTING_RTB_SYNC_STATUS,
	TM_STATUS_RTB_RESYNC_REQUESTED,
	AGT_STATUS_RTB_ALREADY_SYNCED,
	AGT_STATUS_RTB_SYNC_SUCCESSFUL,
	AGT_STATUS_RTB_SYNC_DENIED_DATABASE_NOT_FOUND,
	AGT_STATUS_RTB_SYNC_DENIED_REPOSITORY_NOT_FOUND,
	AGT_STATUS_RTB_SYNC_DENIED_NO_WRITE_PERMISSION
}

export enum MessageFromTMContentType {
	CONNECTION_REQUEST,
	SYNC_VERIFICATIONS,
	DATA_TRANSFER
}