-- Database generated with pgModeler (PostgreSQL Database Modeler).
-- pgModeler  version: 0.9.1-alpha
-- PostgreSQL version: 9.6
-- Project Site: pgmodeler.com.br
-- Model Author: ---


-- Database creation must be done outside an multicommand file.
-- These commands were put in this file only for convenience.
-- -- object: new_database | type: DATABASE --
-- -- DROP DATABASE IF EXISTS new_database;
-- CREATE DATABASE new_database
-- ;
-- -- ddl-end --
-- 

-- object: public."USERS" | type: TABLE --
-- DROP TABLE IF EXISTS public."USERS" CASCADE;
CREATE TABLE public."USERS"(
	"ID" bigserial NOT NULL,
	"HASH" character(128) NOT NULL,
	"IS_INVITATION" boolean NOT NULL,
	CONSTRAINT "USERS_pk" PRIMARY KEY ("ID")

);
-- ddl-end --
ALTER TABLE public."USERS" OWNER TO postgres;
-- ddl-end --

-- object: public."DATABASES" | type: TABLE --
-- DROP TABLE IF EXISTS public."DATABASES" CASCADE;
CREATE TABLE public."DATABASES"(
	"ID" bigserial NOT NULL,
	"ID_SERVERS" integer,
	"ID_USERS" bigint NOT NULL,
	CONSTRAINT "DATABASES_pk" PRIMARY KEY ("ID")

);
-- ddl-end --
ALTER TABLE public."DATABASES" OWNER TO postgres;
-- ddl-end --

-- object: "USERS_fk" | type: CONSTRAINT --
-- ALTER TABLE public."DATABASES" DROP CONSTRAINT IF EXISTS "USERS_fk" CASCADE;
ALTER TABLE public."DATABASES" ADD CONSTRAINT "USERS_fk" FOREIGN KEY ("ID_USERS")
REFERENCES public."USERS" ("ID") MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: public."SERVERS" | type: TABLE --
-- DROP TABLE IF EXISTS public."SERVERS" CASCADE;
CREATE TABLE public."SERVERS"(
	"ID" serial NOT NULL,
	"SERVER_TYPE" smallint NOT NULL,
	CONSTRAINT "SERVERS_pk" PRIMARY KEY ("ID")

);
-- ddl-end --
ALTER TABLE public."SERVERS" OWNER TO postgres;
-- ddl-end --

-- object: "SERVERS_fk" | type: CONSTRAINT --
-- ALTER TABLE public."DATABASES" DROP CONSTRAINT IF EXISTS "SERVERS_fk" CASCADE;
ALTER TABLE public."DATABASES" ADD CONSTRAINT "SERVERS_fk" FOREIGN KEY ("ID_SERVERS")
REFERENCES public."SERVERS" ("ID") MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: public."REPOSITORIES" | type: TABLE --
-- DROP TABLE IF EXISTS public."REPOSITORIES" CASCADE;
CREATE TABLE public."REPOSITORIES"(
	"ID" bigserial NOT NULL,
	last_change_datetime timestamp NOT NULL,
	CONSTRAINT "REPOSITORIES_pk" PRIMARY KEY ("ID")

);
-- ddl-end --
ALTER TABLE public."REPOSITORIES" OWNER TO postgres;
-- ddl-end --

-- object: public."DATABASE_REPOSITORIES" | type: TABLE --
-- DROP TABLE IF EXISTS public."DATABASE_REPOSITORIES" CASCADE;
CREATE TABLE public."DATABASE_REPOSITORIES"(
	"ID_DATABASES" bigint NOT NULL,
	"ID_REPOSITORIES" bigint NOT NULL,
	CONSTRAINT "DATABASE_REPOSITORIES_pk" PRIMARY KEY ("ID_DATABASES","ID_REPOSITORIES")

);
-- ddl-end --
ALTER TABLE public."DATABASE_REPOSITORIES" OWNER TO postgres;
-- ddl-end --

-- object: "DATABASES_fk" | type: CONSTRAINT --
-- ALTER TABLE public."DATABASE_REPOSITORIES" DROP CONSTRAINT IF EXISTS "DATABASES_fk" CASCADE;
ALTER TABLE public."DATABASE_REPOSITORIES" ADD CONSTRAINT "DATABASES_fk" FOREIGN KEY ("ID_DATABASES")
REFERENCES public."DATABASES" ("ID") MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: "REPOSITORIES_fk" | type: CONSTRAINT --
-- ALTER TABLE public."DATABASE_REPOSITORIES" DROP CONSTRAINT IF EXISTS "REPOSITORIES_fk" CASCADE;
ALTER TABLE public."DATABASE_REPOSITORIES" ADD CONSTRAINT "REPOSITORIES_fk" FOREIGN KEY ("ID_REPOSITORIES")
REFERENCES public."REPOSITORIES" ("ID") MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: public."USER_REPOSITORIES" | type: TABLE --
-- DROP TABLE IF EXISTS public."USER_REPOSITORIES" CASCADE;
CREATE TABLE public."USER_REPOSITORIES"(
	"ID_USERS" bigint NOT NULL,
	"ID_REPOSITORIES" bigint NOT NULL,
	CONSTRAINT "USER_REPOSITORIES_pk" PRIMARY KEY ("ID_USERS","ID_REPOSITORIES")

);
-- ddl-end --
ALTER TABLE public."USER_REPOSITORIES" OWNER TO postgres;
-- ddl-end --

-- object: "USERS_fk" | type: CONSTRAINT --
-- ALTER TABLE public."USER_REPOSITORIES" DROP CONSTRAINT IF EXISTS "USERS_fk" CASCADE;
ALTER TABLE public."USER_REPOSITORIES" ADD CONSTRAINT "USERS_fk" FOREIGN KEY ("ID_USERS")
REFERENCES public."USERS" ("ID") MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: "REPOSITORIES_fk" | type: CONSTRAINT --
-- ALTER TABLE public."USER_REPOSITORIES" DROP CONSTRAINT IF EXISTS "REPOSITORIES_fk" CASCADE;
ALTER TABLE public."USER_REPOSITORIES" ADD CONSTRAINT "REPOSITORIES_fk" FOREIGN KEY ("ID_REPOSITORIES")
REFERENCES public."REPOSITORIES" ("ID") MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: public."SYNC_GENERATIONS" | type: TABLE --
-- DROP TABLE IF EXISTS public."SYNC_GENERATIONS" CASCADE;
CREATE TABLE public."SYNC_GENERATIONS"(
	"ID" bigserial NOT NULL,
	"START_DATETIME" timestamp NOT NULL,
	"PROCESSED_DATETIME" timestamp,
	CONSTRAINT "SYNC_GENERATIONS_pk" PRIMARY KEY ("ID")

);
-- ddl-end --
ALTER TABLE public."SYNC_GENERATIONS" OWNER TO postgres;
-- ddl-end --

-- object: public."SERVER_SYNC_LOG" | type: TABLE --
-- DROP TABLE IF EXISTS public."SERVER_SYNC_LOG" CASCADE;
CREATE TABLE public."SERVER_SYNC_LOG"(
	"SYNC_DATETIME" timestamp,
	"ID_SYNC_GENERATIONS" bigint NOT NULL,
	"ID_SERVERS" integer NOT NULL,
	CONSTRAINT "SERVER_SYNC_LOG_pk" PRIMARY KEY ("ID_SYNC_GENERATIONS","ID_SERVERS")

);
-- ddl-end --
ALTER TABLE public."SERVER_SYNC_LOG" OWNER TO postgres;
-- ddl-end --

-- object: "SYNC_GENERATIONS_fk" | type: CONSTRAINT --
-- ALTER TABLE public."SERVER_SYNC_LOG" DROP CONSTRAINT IF EXISTS "SYNC_GENERATIONS_fk" CASCADE;
ALTER TABLE public."SERVER_SYNC_LOG" ADD CONSTRAINT "SYNC_GENERATIONS_fk" FOREIGN KEY ("ID_SYNC_GENERATIONS")
REFERENCES public."SYNC_GENERATIONS" ("ID") MATCH FULL
ON DELETE CASCADE ON UPDATE CASCADE;
-- ddl-end --

-- object: public."REPOSITORY_SYNC_LOG" | type: TABLE --
-- DROP TABLE IF EXISTS public."REPOSITORY_SYNC_LOG" CASCADE;
CREATE TABLE public."REPOSITORY_SYNC_LOG"(
	"ADD_DATETIME" timestamp NOT NULL,
	"ID_REPOSITORIES" bigint NOT NULL,
	"ID_DATABASES" bigint NOT NULL,
	"ID_SYNC_GENERATIONS" bigint NOT NULL,
	"ID_USERS" bigint,
	CONSTRAINT "REPOSITORY_SYNC_LOG_pk" PRIMARY KEY ("ADD_DATETIME","ID_REPOSITORIES","ID_DATABASES")

);
-- ddl-end --
ALTER TABLE public."REPOSITORY_SYNC_LOG" OWNER TO postgres;
-- ddl-end --

-- object: "REPOSITORIES_fk" | type: CONSTRAINT --
-- ALTER TABLE public."REPOSITORY_SYNC_LOG" DROP CONSTRAINT IF EXISTS "REPOSITORIES_fk" CASCADE;
ALTER TABLE public."REPOSITORY_SYNC_LOG" ADD CONSTRAINT "REPOSITORIES_fk" FOREIGN KEY ("ID_REPOSITORIES")
REFERENCES public."REPOSITORIES" ("ID") MATCH FULL
ON DELETE CASCADE ON UPDATE CASCADE;
-- ddl-end --

-- object: "DATABASES_fk" | type: CONSTRAINT --
-- ALTER TABLE public."REPOSITORY_SYNC_LOG" DROP CONSTRAINT IF EXISTS "DATABASES_fk" CASCADE;
ALTER TABLE public."REPOSITORY_SYNC_LOG" ADD CONSTRAINT "DATABASES_fk" FOREIGN KEY ("ID_DATABASES")
REFERENCES public."DATABASES" ("ID") MATCH FULL
ON DELETE CASCADE ON UPDATE CASCADE;
-- ddl-end --

-- object: "SYNC_GENERATIONS_fk" | type: CONSTRAINT --
-- ALTER TABLE public."REPOSITORY_SYNC_LOG" DROP CONSTRAINT IF EXISTS "SYNC_GENERATIONS_fk" CASCADE;
ALTER TABLE public."REPOSITORY_SYNC_LOG" ADD CONSTRAINT "SYNC_GENERATIONS_fk" FOREIGN KEY ("ID_SYNC_GENERATIONS")
REFERENCES public."SYNC_GENERATIONS" ("ID") MATCH FULL
ON DELETE RESTRICT ON UPDATE CASCADE;
-- ddl-end --

-- object: "USERS_fk" | type: CONSTRAINT --
-- ALTER TABLE public."REPOSITORY_SYNC_LOG" DROP CONSTRAINT IF EXISTS "USERS_fk" CASCADE;
ALTER TABLE public."REPOSITORY_SYNC_LOG" ADD CONSTRAINT "USERS_fk" FOREIGN KEY ("ID_USERS")
REFERENCES public."USERS" ("ID") MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: "SERVERS_fk" | type: CONSTRAINT --
-- ALTER TABLE public."SERVER_SYNC_LOG" DROP CONSTRAINT IF EXISTS "SERVERS_fk" CASCADE;
ALTER TABLE public."SERVER_SYNC_LOG" ADD CONSTRAINT "SERVERS_fk" FOREIGN KEY ("ID_SERVERS")
REFERENCES public."SERVERS" ("ID") MATCH FULL
ON DELETE CASCADE ON UPDATE CASCADE;
-- ddl-end --


