import { Token } from "typedi";
import { ITMDataDeserializer } from "./impl/data/TMDataDeserializer";
import { ITMDataFormatVerifier } from "./impl/data/TMDataFormatVerifier";
import { ITMDataSchemaVerifier } from "./impl/data/TMDataSchemaVerifier";
import { ITMDataSerializer } from "./impl/data/TMDataSerializer";
import { IMessageFromTMDeserializer } from "./impl/message/deserializer/MessageFromTMDeserializer";
import { IMessageToTMDeserializer } from "./impl/message/deserializer/MessageToTMDeserializer";
import { IMessageFromTMSerializer } from "./impl/message/serializer/MessageFromTMSerializer";
import { IMessageToTMSerializer } from "./impl/message/serializer/MessageToTMSerializer";
import { IMessageFromTMVerifier } from "./impl/message/verifier/MessageFromTMVerifier";
import { IMessageToTMVerifier } from "./impl/message/verifier/MessageToTMVerifier";
import { ISyncConnectionServer } from "./lingo/SyncConnectionServer";
export declare const MessageFromTMDeserializerToken: Token<IMessageFromTMDeserializer>;
export declare const MessageFromTMSerializerToken: Token<IMessageFromTMSerializer>;
export declare const MessageFromTMVerifierToken: Token<IMessageFromTMVerifier>;
export declare const MessageToTMDeserializerToken: Token<IMessageToTMDeserializer>;
export declare const MessageToTMSerializerToken: Token<IMessageToTMSerializer>;
export declare const MessageToTMVerifierToken: Token<IMessageToTMVerifier>;
export declare const SyncConnectionServerToken: Token<ISyncConnectionServer<any, any, any, any>>;
export declare const TMDataSerializerToken: Token<ITMDataSerializer>;
export declare const TMDataDeserializerToken: Token<ITMDataDeserializer>;
export declare const TMDataFormatVerifierToken: Token<ITMDataFormatVerifier>;
export declare const TMDataSchemaVerifierToken: Token<ITMDataSchemaVerifier>;
