import { ILoggedApplication, ILoggedPackage } from "@airport/approach-lighting-system";
export declare const DatabaseManagerToken: any;
export declare const DeleteManagerToken: any;
export declare const HistoryManagerToken: any;
export declare const InsertManagerToken: any;
export declare const OfflineDeltaStoreToken: any;
export declare const OnlineManagerToken: any;
export declare const QueryManagerToken: any;
export declare const RepositoryManagerToken: any;
export declare const StoreDriverToken: any;
export declare const UpdateManagerToken: any;
export declare const TerminalLogger: ILoggedPackage;
export declare const TerminalAppLogger: ILoggedApplication;
