export var MessageToTMError;
(function (MessageToTMError) {
    MessageToTMError["NO_DATA_ERROR"] = "NO_DATA_ERROR";
    MessageToTMError["MESSAGE_IS_NOT_ARRAY"] = "MESSAGE_IS_NOT_ARRAY";
    MessageToTMError["PROTOCOL_VERSION_NOT_SUPPORTED"] = "PROTOCOL_VERSION_NOT_SUPPORTED";
    MessageToTMError["MESSAGE_TYPE_IS_NOT_NUMBER"] = "MESSAGE_TYPE_IS_NOT_NUMBER";
    MessageToTMError["MESSAGES_BATCH_IS_NOT_ARRAY"] = "MESSAGES_BATCH_IS_NOT_ARRAY";
    MessageToTMError["WRONG_MESSAGES_BATCH_LENGTH"] = "WRONG_MESSAGES_BATCH_LENGTH";
    MessageToTMError["TARGET_AGT_DATABASE_IDS_IS_NOT_ARRAY"] = "TARGET_AGT_DATABASE_IDS_IS_NOT_ARRAY";
    MessageToTMError["TARGET_AGT_DATABASE_ID_IS_NOT_NUMBER"] = "TARGET_AGT_DATABASE_ID_IS_NOT_NUMBER";
    MessageToTMError["TARGET_AGT_DATABASE_ID_IS_INVALID_NUMBER"] = "TARGET_AGT_DATABASE_ID_IS_INVALID_NUMBER";
    MessageToTMError["AGT_DATABASE_SYNC_LOG_ID_IS_NOT_NUMBER"] = "AGT_DATABASE_SYNC_LOG_ID_IS_NOT_NUMBER";
    MessageToTMError["AGT_DATABASE_SYNC_LOG_ID_IS_INVALID_NUMBER"] = "AGT_DATABASE_SYNC_LOG_ID_IS_INVALID_NUMBER";
    MessageToTMError["MESSAGES_IS_NOT_ARRAY"] = "MESSAGES_IS_NOT_ARRAY";
    // NO_MESSAGES_IN_ARRAY = 'NO_MESSAGES_IN_ARRAY', // No messages is OK
    MessageToTMError["WRONG_CONTENT_TYPE"] = "WRONG_CONTENT_TYPE";
    MessageToTMError["UNSUPPORTED_CONTENT_TYPE"] = "UNSUPPORTED_CONTENT_TYPE";
    MessageToTMError["TM_SHARING_MESSAGE_ID_IS_NOT_NUMBER"] = "TM_SHARING_MESSAGE_ID_IS_NOT_NUMBER";
    MessageToTMError["AGT_SYNC_RECORD_ADD_DATETIME_IS_NOT_NUMBER"] = "AGT_SYNC_RECORD_ADD_DATETIME_IS_NOT_NUMBER";
    MessageToTMError["TM_REPOSITORY_TRANSACTION_BLOCK_ID_IS_NOT_NUMBER"] = "TM_REPOSITORY_TRANSACTION_BLOCK_ID_IS_NOT_NUMBER";
    MessageToTMError["AGT_SYNC_RECORD_ID_IS_NOT_NUMBER"] = "AGT_SYNC_RECORD_ID_IS_NOT_NUMBER";
    MessageToTMError["WRONG_REPO_TRANS_BLOCK_SYNC_OUTCOME_TYPE"] = "WRONG_REPO_TRANS_BLOCK_SYNC_OUTCOME_TYPE";
    MessageToTMError["AGT_DATABASE_ID_IS_NOT_NUMBER"] = "AGT_DATABASE_ID_IS_NOT_NUMBER";
    MessageToTMError["AGT_REPOSITORY_ID_IS_NOT_NUMBER"] = "AGT_REPOSITORY_ID_IS_NOT_NUMBER";
    MessageToTMError["AGT_SYNC_RECORD_REPOSITORY_TRANSACTION_BLOCK_IS_NOT_STRING"] = "AGT_SYNC_RECORD_REPOSITORY_TRANSACTION_BLOCK_IS_NOT_STRING";
})(MessageToTMError || (MessageToTMError = {}));
//# sourceMappingURL=MessageToTMError.js.map