export var MessageToTMError;
(function (MessageToTMError) {
    MessageToTMError[MessageToTMError["NO_DATA_ERROR"] = 0] = "NO_DATA_ERROR";
    MessageToTMError[MessageToTMError["MESSAGE_IS_NOT_ARRAY"] = 1] = "MESSAGE_IS_NOT_ARRAY";
    MessageToTMError[MessageToTMError["PROTOCOL_VERSION_NOT_SUPPORTED"] = 2] = "PROTOCOL_VERSION_NOT_SUPPORTED";
    MessageToTMError[MessageToTMError["MESSAGE_TYPE_IS_NOT_NUMBER"] = 3] = "MESSAGE_TYPE_IS_NOT_NUMBER";
    MessageToTMError[MessageToTMError["MESSAGES_BATCH_IS_NOT_ARRAY"] = 4] = "MESSAGES_BATCH_IS_NOT_ARRAY";
    MessageToTMError[MessageToTMError["WRONG_MESSAGES_BATCH_LENGTH"] = 5] = "WRONG_MESSAGES_BATCH_LENGTH";
    MessageToTMError[MessageToTMError["TARGET_AGT_DATABASE_IDS_IS_NOT_ARRAY"] = 6] = "TARGET_AGT_DATABASE_IDS_IS_NOT_ARRAY";
    MessageToTMError[MessageToTMError["TARGET_AGT_DATABASE_ID_IS_NOT_NUMBER"] = 7] = "TARGET_AGT_DATABASE_ID_IS_NOT_NUMBER";
    MessageToTMError[MessageToTMError["TARGET_AGT_DATABASE_ID_IS_INVALID_NUMBER"] = 8] = "TARGET_AGT_DATABASE_ID_IS_INVALID_NUMBER";
    MessageToTMError[MessageToTMError["AGT_DATABASE_SYNC_LOG_ID_IS_NOT_NUMBER"] = 9] = "AGT_DATABASE_SYNC_LOG_ID_IS_NOT_NUMBER";
    MessageToTMError[MessageToTMError["AGT_DATABASE_SYNC_LOG_ID_IS_INVALID_NUMBER"] = 10] = "AGT_DATABASE_SYNC_LOG_ID_IS_INVALID_NUMBER";
    MessageToTMError[MessageToTMError["MESSAGES_IS_NOT_ARRAY"] = 11] = "MESSAGES_IS_NOT_ARRAY";
    // NO_MESSAGES_IN_ARRAY, // No messages is OK
    MessageToTMError[MessageToTMError["WRONG_CONTENT_TYPE"] = 12] = "WRONG_CONTENT_TYPE";
    MessageToTMError[MessageToTMError["UNSUPPORTED_CONTENT_TYPE"] = 13] = "UNSUPPORTED_CONTENT_TYPE";
    MessageToTMError[MessageToTMError["TM_SHARING_MESSAGE_ID_IS_NOT_NUMBER"] = 14] = "TM_SHARING_MESSAGE_ID_IS_NOT_NUMBER";
    MessageToTMError[MessageToTMError["AGT_SYNC_RECORD_ADD_DATETIME_IS_NOT_NUMBER"] = 15] = "AGT_SYNC_RECORD_ADD_DATETIME_IS_NOT_NUMBER";
    MessageToTMError[MessageToTMError["TM_REPOSITORY_TRANSACTION_BLOCK_ID_IS_NOT_NUMBER"] = 16] = "TM_REPOSITORY_TRANSACTION_BLOCK_ID_IS_NOT_NUMBER";
    MessageToTMError[MessageToTMError["AGT_SYNC_RECORD_ID_IS_NOT_NUMBER"] = 17] = "AGT_SYNC_RECORD_ID_IS_NOT_NUMBER";
    MessageToTMError[MessageToTMError["WRONG_REPO_TRANS_BLOCK_SYNC_OUTCOME_TYPE"] = 18] = "WRONG_REPO_TRANS_BLOCK_SYNC_OUTCOME_TYPE";
    MessageToTMError[MessageToTMError["AGT_DATABASE_ID_IS_NOT_NUMBER"] = 19] = "AGT_DATABASE_ID_IS_NOT_NUMBER";
    MessageToTMError[MessageToTMError["AGT_REPOSITORY_ID_IS_NOT_NUMBER"] = 20] = "AGT_REPOSITORY_ID_IS_NOT_NUMBER";
    MessageToTMError[MessageToTMError["AGT_SYNC_RECORD_REPOSITORY_TRANSACTION_BLOCK_IS_NOT_STRING"] = 21] = "AGT_SYNC_RECORD_REPOSITORY_TRANSACTION_BLOCK_IS_NOT_STRING";
})(MessageToTMError || (MessageToTMError = {}));
//# sourceMappingURL=MessageToTMError.js.map