import { ISharingNodeEndpoint } from './synchronization/connect/SharingNodeEndpoint';
import { ISyncInActorChecker } from './synchronization/in/checker/SyncInActorChecker';
import { ISyncInChecker } from './synchronization/in/checker/SyncInChecker';
import { ISyncInConsistencyChecker } from './synchronization/in/checker/SyncInConsistencyChecker';
import { ISyncInDataChecker } from './synchronization/in/checker/SyncInDataChecker';
import { ISyncInRepositoryChecker } from './synchronization/in/checker/SyncInRepositoryChecker';
import { ISyncInSchemaChecker } from './synchronization/in/checker/SyncInSchemaChecker';
import { ISyncInTerminalChecker } from './synchronization/in/checker/SyncInTerminalChecker';
import { ISyncInUserChecker } from './synchronization/in/checker/SyncInUserChecker';
import { IMissingRecordCreator } from './synchronization/in/creator/MissingRecordCreator';
import { ISyncInRepositoryTransactionBlockCreator } from './synchronization/in/creator/SyncInRepositoryTransactionBlockCreator';
import { ISyncInSharingMessageCreator } from './synchronization/in/creator/SyncInSharingMessageCreator';
import { IStage1SyncedInDataProcessor } from './synchronization/in/Stage1SyncedInDataProcessor';
import { IStage2SyncedInDataProcessor } from './synchronization/in/Stage2SyncedInDataProcessor';
import { ISynchronizationInManager } from './synchronization/in/SynchronizationInManager';
import { ISyncInUtils } from './synchronization/in/SyncInUtils';
import { ISyncLogMessageProcessor } from './synchronization/in/SyncLogMessageProcessor';
import { ITwoStageSyncedInDataProcessor } from './synchronization/in/TwoStageSyncedInDataProcessor';
import { ISynchronizationOutCoordinator } from './synchronization/out/SynchronizationOutCoordinator';
import { ISynchronizationOutManager } from './synchronization/out/SynchronizationOutManager';
import { ISyncOutMessageSender } from './synchronization/out/SyncOutMessageSender';
import { ISyncOutRepositoryTransactionBlockCreator } from './synchronization/out/SyncOutRepositoryTransactionBlockCreator';
import { ISyncOutSerializer } from './synchronization/out/SyncOutSerializer';
import { ISyncNodeManager } from './synchronization/SyncNodeManager';
export declare const DIRECT_SHARING_NODE_ENDPOINT: import("@airport/di").IDiToken<ISharingNodeEndpoint>;
export declare const HTTP_SHARING_NODE_ENDPOINT: import("@airport/di").IDiToken<ISharingNodeEndpoint>;
export declare const MISSING_RECORD_CREATOR: import("@airport/di").IDiToken<IMissingRecordCreator>;
export declare const STAGE1_SYNCED_IN_DATA_PROCESSOR: import("@airport/di").IDiToken<IStage1SyncedInDataProcessor>;
export declare const STAGE2_SYNCED_IN_DATA_PROCESSOR: import("@airport/di").IDiToken<IStage2SyncedInDataProcessor>;
export declare const SYNC_IN_ACTOR_CHECKER: import("@airport/di").IDiToken<ISyncInActorChecker>;
export declare const SYNC_IN_CHECKER: import("@airport/di").IDiToken<ISyncInChecker>;
export declare const SYNC_IN_CONSISTENCY_CHECKER: import("@airport/di").IDiToken<ISyncInConsistencyChecker>;
export declare const SYNC_IN_DATA_CHECKER: import("@airport/di").IDiToken<ISyncInDataChecker>;
export declare const SYNC_IN_TERMINAL_CHECKER: import("@airport/di").IDiToken<ISyncInTerminalChecker>;
export declare const SYNC_IN_REPO_CHECKER: import("@airport/di").IDiToken<ISyncInRepositoryChecker>;
export declare const SYNC_IN_REPO_TRANS_BLOCK_CREATOR: import("@airport/di").IDiToken<ISyncInRepositoryTransactionBlockCreator>;
export declare const SYNC_IN_SCHEMA_CHECKER: import("@airport/di").IDiToken<ISyncInSchemaChecker>;
export declare const SYNC_IN_SHARING_MESSAGE_CREATOR: import("@airport/di").IDiToken<ISyncInSharingMessageCreator>;
export declare const SYNC_IN_USER_CHECKER: import("@airport/di").IDiToken<ISyncInUserChecker>;
export declare const SYNC_IN_UTILS: import("@airport/di").IDiToken<ISyncInUtils>;
export declare const SYNC_LOG_MESSAGE_PROCESSOR: import("@airport/di").IDiToken<ISyncLogMessageProcessor>;
export declare const SYNC_NODE_MANAGER: import("@airport/di").IDiToken<ISyncNodeManager>;
export declare const SYNC_IN_MANAGER: import("@airport/di").IDiToken<ISynchronizationInManager>;
export declare const SYNC_OUT_COORDINATOR: import("@airport/di").IDiToken<ISynchronizationOutCoordinator>;
export declare const SYNC_OUT_MANAGER: import("@airport/di").IDiToken<ISynchronizationOutManager>;
export declare const SYNC_OUT_MSG_SENDER: import("@airport/di").IDiToken<ISyncOutMessageSender>;
export declare const SYNC_OUT_REPO_TRANS_BLOCK_CREATOR: import("@airport/di").IDiToken<ISyncOutRepositoryTransactionBlockCreator>;
export declare const SYNC_OUT_SERIALIZER: import("@airport/di").IDiToken<ISyncOutSerializer>;
export declare const TWO_STAGE_SYNCED_IN_DATA_PROCESSOR: import("@airport/di").IDiToken<ITwoStageSyncedInDataProcessor>;
