import { ISyncInActorChecker } from './synchronization/in/checker/SyncInActorChecker';
import { ISyncInChecker } from './synchronization/in/checker/SyncInChecker';
import { ISyncInDataChecker } from './synchronization/in/checker/SyncInDataChecker';
import { ISyncInRepositoryChecker } from './synchronization/in/checker/SyncInRepositoryChecker';
import { ISyncInApplicationChecker } from './synchronization/in/checker/SyncInApplicationChecker';
import { ISyncInApplicationVersionChecker } from './synchronization/in/checker/SyncInApplicationVersionChecker';
import { ISyncInTerminalChecker } from './synchronization/in/checker/SyncInTerminalChecker';
import { ISyncInUserChecker } from './synchronization/in/checker/SyncInUserChecker';
import { IStage1SyncedInDataProcessor } from './synchronization/in/Stage1SyncedInDataProcessor';
import { IStage2SyncedInDataProcessor } from './synchronization/in/Stage2SyncedInDataProcessor';
import { ISynchronizationInManager } from './synchronization/in/SynchronizationInManager';
import { ISyncInUtils } from './synchronization/in/SyncInUtils';
import { ITwoStageSyncedInDataProcessor } from './synchronization/in/TwoStageSyncedInDataProcessor';
import { ISynchronizationOutCoordinator } from './synchronization/out/SynchronizationOutCoordinator';
import { ISynchronizationOutManager } from './synchronization/out/SynchronizationOutManager';
import { ISyncOutMessageSender } from './synchronization/out/SyncOutMessageSender';
import { ISyncOutRepositoryTransactionBlockCreator } from './synchronization/out/SyncOutRepositoryTransactionBlockCreator';
import { ISyncOutSerializer } from './synchronization/out/SyncOutSerializer';
import { ISyncNodeManager } from './synchronization/SyncNodeManager';
import { ISynchronizationAdapter } from './adapters/ISynchronizationAdapter';
import { ISynchronizationAdapterLoader } from './adapters/SynchronizationAdapterLoader';
export declare const STAGE1_SYNCED_IN_DATA_PROCESSOR: import("@airport/di").IDiToken<IStage1SyncedInDataProcessor>;
export declare const STAGE2_SYNCED_IN_DATA_PROCESSOR: import("@airport/di").IDiToken<IStage2SyncedInDataProcessor>;
export declare const SYNC_IN_ACTOR_CHECKER: import("@airport/di").IDiToken<ISyncInActorChecker>;
export declare const SYNC_IN_CHECKER: import("@airport/di").IDiToken<ISyncInChecker>;
export declare const SYNC_IN_DATA_CHECKER: import("@airport/di").IDiToken<ISyncInDataChecker>;
export declare const SYNC_IN_TERMINAL_CHECKER: import("@airport/di").IDiToken<ISyncInTerminalChecker>;
export declare const SYNC_IN_REPOSITORY_CHECKER: import("@airport/di").IDiToken<ISyncInRepositoryChecker>;
export declare const SYNC_IN_APPLICATION_CHECKER: import("@airport/di").IDiToken<ISyncInApplicationChecker>;
export declare const SYNC_IN_APPLICATION_VERSION_CHECKER: import("@airport/di").IDiToken<ISyncInApplicationVersionChecker>;
export declare const SYNC_IN_USER_CHECKER: import("@airport/di").IDiToken<ISyncInUserChecker>;
export declare const SYNC_IN_UTILS: import("@airport/di").IDiToken<ISyncInUtils>;
export declare const SYNC_NODE_MANAGER: import("@airport/di").IDiToken<ISyncNodeManager>;
export declare const SYNCHRONIZATION_IN_MANAGER: import("@airport/di").IDiToken<ISynchronizationInManager>;
export declare const SYNCHRONIZATION_OUT_COORDINATOR: import("@airport/di").IDiToken<ISynchronizationOutCoordinator>;
export declare const SYNCHRONIZATION_OUT_MANAGER: import("@airport/di").IDiToken<ISynchronizationOutManager>;
export declare const SYNC_OUT_MESSAGE_SENDER: import("@airport/di").IDiToken<ISyncOutMessageSender>;
export declare const SYNC_OUT_REPOSITORY_TRANSACTION_BLOCK_CREATOR: import("@airport/di").IDiToken<ISyncOutRepositoryTransactionBlockCreator>;
export declare const SYNC_OUT_SERIALIZER: import("@airport/di").IDiToken<ISyncOutSerializer>;
export declare const TWO_STAGE_SYNCED_IN_DATA_PROCESSOR: import("@airport/di").IDiToken<ITwoStageSyncedInDataProcessor>;
export declare const DEBUG_SYNCHRONIZATION_ADAPTER: import("@airport/di").IDiToken<ISynchronizationAdapter>;
export declare const SYNCHRONIZATION_ADAPTER_LOADER: import("@airport/di").IDiToken<ISynchronizationAdapterLoader>;
//# sourceMappingURL=tokens.d.ts.map