import { ISyncInActorChecker } from './synchronization/in/checker/SyncInActorChecker';
import { ISyncInChecker } from './synchronization/in/checker/SyncInChecker';
import { ISyncInDataChecker } from './synchronization/in/checker/SyncInDataChecker';
import { ISyncInRepositoryChecker } from './synchronization/in/checker/SyncInRepositoryChecker';
import { ISyncInApplicationChecker } from './synchronization/in/checker/SyncInApplicationChecker';
import { ISyncInApplicationVersionChecker } from './synchronization/in/checker/SyncInApplicationVersionChecker';
import { ISyncInTerminalChecker } from './synchronization/in/checker/SyncInTerminalChecker';
import { ISyncInUserChecker } from './synchronization/in/checker/SyncInUserChecker';
import { IStage1SyncedInDataProcessor } from './synchronization/in/Stage1SyncedInDataProcessor';
import { IStage2SyncedInDataProcessor } from './synchronization/in/Stage2SyncedInDataProcessor';
import { ISynchronizationInManager } from './synchronization/in/SynchronizationInManager';
import { ISyncInUtils } from './synchronization/in/SyncInUtils';
import { ITwoStageSyncedInDataProcessor } from './synchronization/in/TwoStageSyncedInDataProcessor';
import { ISynchronizationOutManager } from './synchronization/out/SynchronizationOutManager';
import { ISynchronizationAdapter } from './adapters/ISynchronizationAdapter';
import { ISynchronizationAdapterLoader } from './adapters/SynchronizationAdapterLoader';
import { ISyncOutDataSerializer } from './synchronization/out/converter/SyncOutDataSerializer';
export declare const STAGE1_SYNCED_IN_DATA_PROCESSOR: import("@airport/direction-indicator").IDependencyInjectionToken<IStage1SyncedInDataProcessor>;
export declare const STAGE2_SYNCED_IN_DATA_PROCESSOR: import("@airport/direction-indicator").IDependencyInjectionToken<IStage2SyncedInDataProcessor>;
export declare const SYNC_IN_ACTOR_CHECKER: import("@airport/direction-indicator").IDependencyInjectionToken<ISyncInActorChecker>;
export declare const SYNC_IN_CHECKER: import("@airport/direction-indicator").IDependencyInjectionToken<ISyncInChecker>;
export declare const SYNC_IN_DATA_CHECKER: import("@airport/direction-indicator").IDependencyInjectionToken<ISyncInDataChecker>;
export declare const SYNC_IN_TERMINAL_CHECKER: import("@airport/direction-indicator").IDependencyInjectionToken<ISyncInTerminalChecker>;
export declare const SYNC_IN_REPOSITORY_CHECKER: import("@airport/direction-indicator").IDependencyInjectionToken<ISyncInRepositoryChecker>;
export declare const SYNC_IN_APPLICATION_CHECKER: import("@airport/direction-indicator").IDependencyInjectionToken<ISyncInApplicationChecker>;
export declare const SYNC_IN_APPLICATION_VERSION_CHECKER: import("@airport/direction-indicator").IDependencyInjectionToken<ISyncInApplicationVersionChecker>;
export declare const SYNC_IN_USER_CHECKER: import("@airport/direction-indicator").IDependencyInjectionToken<ISyncInUserChecker>;
export declare const SYNC_IN_UTILS: import("@airport/direction-indicator").IDependencyInjectionToken<ISyncInUtils>;
export declare const SYNCHRONIZATION_IN_MANAGER: import("@airport/direction-indicator").IDependencyInjectionToken<ISynchronizationInManager>;
export declare const SYNCHRONIZATION_OUT_MANAGER: import("@airport/direction-indicator").IDependencyInjectionToken<ISynchronizationOutManager>;
export declare const SYNC_OUT_DATA_SERIALIZER: import("@airport/direction-indicator").IDependencyInjectionToken<ISyncOutDataSerializer>;
export declare const TWO_STAGE_SYNCED_IN_DATA_PROCESSOR: import("@airport/direction-indicator").IDependencyInjectionToken<ITwoStageSyncedInDataProcessor>;
export declare const DEBUG_SYNCHRONIZATION_ADAPTER: import("@airport/direction-indicator").IDependencyInjectionToken<ISynchronizationAdapter>;
export declare const SYNCHRONIZATION_ADAPTER_LOADER: import("@airport/direction-indicator").IDependencyInjectionToken<ISynchronizationAdapterLoader>;
//# sourceMappingURL=tokens.d.ts.map