export var ServerErrorType;
(function (ServerErrorType) {
    ServerErrorType["DUPLICATE_INCOMING_DATABASE_KEYS_HAVE_NO_MATCHING_DATABASE"] = "DUPLICATE_INCOMING_DATABASE_KEYS_HAVE_NO_MATCHING_DATABASE";
    ServerErrorType["DUPLICATE_INCOMING_DATABASE_KEYS_HAVE_INCORRECT_HASH"] = "DUPLICATE_INCOMING_DATABASE_KEYS_HAVE_INCORRECT_HASH";
    ServerErrorType["INCOMING_DATABASE_HASH_DOES_NOT_MATCH"] = "INCOMING_DATABASE_HASH_DOES_NOT_MATCH";
    ServerErrorType["INCOMING_DATABASE_KEY_APPEARS_MORE_THAN_ONCE_IN_THE_BATCH"] = "INCOMING_DATABASE_KEY_APPEARS_MORE_THAN_ONCE_IN_THE_BATCH";
    ServerErrorType["INCOMING_DATABASE_SYNC_LOG_KEY_APPEARS_MORE_THAN_ONCE_IN_A_REQUEST"] = "INCOMING_DATABASE_SYNC_LOG_KEY_APPEARS_MORE_THAN_ONCE_IN_A_REQUEST";
    ServerErrorType["INCOMING_DATABASE_RECORD_WASNT_IN_DATABASES_TABLE"] = "INCOMING_DATABASE_RECORD_WASNT_IN_DATABASES_TABLE";
    ServerErrorType["INCOMING_REPOSITORY_REPOSITORY_ID_NOT_FOUND"] = "INCOMING_REPOSITORY_REPOSITORY_ID_NOT_FOUND";
    ServerErrorType["MULTIPLE_DUPLICATE_INCOMING_DATABASE_KEYS_HAVE_CORRECT_HASH"] = "MULTIPLE_DUPLICATE_INCOMING_DATABASE_KEYS_HAVE_CORRECT_HASH";
    ServerErrorType["SYNC_CLIENT_CONNECTED_TOO_SOON"] = "SYNC_CLIENT_CONNECTED_TOO_SOON";
})(ServerErrorType || (ServerErrorType = {}));
//# sourceMappingURL=ServerErrorType.js.map