export enum ServerState {
    RUNNING = 'RUNNING',
    SHUTTING_DOWN_REQUESTS = 'SHUTTING_DOWN_REQUESTS',
    SHUTTING_DOWN_SERVER = 'SHUTTING_DOWN_SERVER',
}

export enum ServerError {
    DATABASE = 'DATABASE',
    INVALID = 'INVALID',
    SHUTDOWN = 'SHUTDOWN'
}
