import { IRepositoryLoader } from '.';
import { IRelationManager } from './impl/core/entity/RelationManager';
import { IQueryContextLoader } from './impl/query/QueryContext';
import { IAirportDatabase } from './lingo/AirportDatabase';
import { IDatabaseFacade, IQueryFacade } from './lingo/core/repository/DatabaseFacade';
import { IUpdateCacheManager } from './lingo/core/UpdateCacheManager';
import { ILookup } from './lingo/query/api/Lookup';
import { IEntityUtils } from './lingo/utils/EntityUtils';
import { IFieldUtils } from './lingo/utils/FieldUtils';
import { IQMetadataUtils } from './lingo/utils/QMetadataUtils';
import { IQueryUtils } from './lingo/utils/QueryUtils';
import { IApplicationUtils } from './lingo/utils/ApplicationUtils';
export declare const AIRPORT_DATABASE: import("@airport/di").IDiToken<IAirportDatabase>;
export declare const DATABASE_FACADE: import("@airport/di").IDiToken<IDatabaseFacade>;
export declare const LOOKUP: import("@airport/di").IDiToken<ILookup>;
export declare const ENTITY_UTILS: import("@airport/di").IDiToken<IEntityUtils>;
export declare const FIELD_UTILS: import("@airport/di").IDiToken<IFieldUtils>;
export declare const Q_METADATA_UTILS: import("@airport/di").IDiToken<IQMetadataUtils>;
export declare const QUERY_CONTEXT_LOADER: import("@airport/di").IDiToken<IQueryContextLoader>;
export declare const QUERY_FACADE: import("@airport/di").IDiToken<IQueryFacade>;
export declare const QUERY_UTILS: import("@airport/di").IDiToken<IQueryUtils>;
export declare const RELATION_MANAGER: import("@airport/di").IDiToken<IRelationManager>;
export declare const REPOSITORY_LOADER: import("@airport/di").IDiToken<IRepositoryLoader>;
export declare const APPLICATION_UTILS: import("@airport/di").IDiToken<IApplicationUtils>;
export declare const UPDATE_CACHE_MANAGER: import("@airport/di").IDiToken<IUpdateCacheManager>;
//# sourceMappingURL=tokens.d.ts.map