import { NPMJS_ORG___AIRPORT_TRAFFIC_PATTERN_Daos } from './dao/dao';
import { ISchemaColumnDao } from './dao/SchemaColumnDao';
import { ISchemaDao } from './dao/SchemaDao';
import { ISchemaEntityDao } from './dao/SchemaEntityDao';
import { ISchemaPropertyColumnDao } from './dao/SchemaPropertyColumnDao';
import { ISchemaPropertyDao } from './dao/SchemaPropertyDao';
import { ISchemaReferenceDao } from './dao/SchemaReferenceDao';
import { ISchemaRelationColumnDao } from './dao/SchemaRelationColumnDao';
import { ISchemaRelationDao } from './dao/SchemaRelationDao';
import { ISchemaVersionDao } from './dao/SchemaVersionDao';
import { NPMJS_ORG___AIRPORT_TRAFFIC_PATTERN_Dmos } from './dmo/dmo';
import { ISchemaVersionDmo } from './dmo/SchemaVersionDmo';
export declare const NPMJS_ORG___AIRPORT_TRAFFIC_PATTERN_QSCHEMA = "NPMJS_ORG___AIRPORT_TRAFFIC_PATTERN_QSCHEMA";
export declare const NPMJS_ORG___AIRPORT_TRAFFIC_PATTERN_DAOS: import("@airport/di").DiToken<NPMJS_ORG___AIRPORT_TRAFFIC_PATTERN_Daos>;
export declare const NPMJS_ORG___AIRPORT_TRAFFIC_PATTERN_DMOS: import("@airport/di").DiToken<NPMJS_ORG___AIRPORT_TRAFFIC_PATTERN_Dmos>;
export declare const SCHEMA_COLUMN_DAO: import("@airport/di").DiToken<ISchemaColumnDao>;
export declare const SCHEMA_DAO: import("@airport/di").DiToken<ISchemaDao>;
export declare const SCHEMA_ENTITY_DAO: import("@airport/di").DiToken<ISchemaEntityDao>;
export declare const SCHEMA_PROPERTY_COLUMN_DAO: import("@airport/di").DiToken<ISchemaPropertyColumnDao>;
export declare const SCHEMA_PROPERTY_DAO: import("@airport/di").DiToken<ISchemaPropertyDao>;
export declare const SCHEMA_REFERENCE_DAO: import("@airport/di").DiToken<ISchemaReferenceDao>;
export declare const SCHEMA_RELATION_COLUMN_DAO: import("@airport/di").DiToken<ISchemaRelationColumnDao>;
export declare const SCHEMA_RELATION_DAO: import("@airport/di").DiToken<ISchemaRelationDao>;
export declare const SCHEMA_VERSION_DAO: import("@airport/di").DiToken<ISchemaVersionDao>;
export declare const SCHEMA_VERSION_DMO: import("@airport/di").DiToken<ISchemaVersionDmo>;
