export declare const NPMJS_ORG___AIRPORT_TRAFFIC_PATTERN_QSCHEMA = "NPMJS_ORG___AIRPORT_TRAFFIC_PATTERN_QSCHEMA";
export declare const NPMJS_ORG___AIRPORT_TRAFFIC_PATTERN_DAOS: any;
export declare const NPMJS_ORG___AIRPORT_TRAFFIC_PATTERN_DMOS: any;
export declare const SCHEMA_COLUMN_DAO: any;
export declare const SCHEMA_DAO: any;
export declare const SCHEMA_ENTITY_DAO: any;
export declare const SCHEMA_PROPERTY_COLUMN_DAO: any;
export declare const SCHEMA_PROPERTY_DAO: any;
export declare const SCHEMA_REFERENCE_DAO: any;
export declare const SCHEMA_RELATION_COLUMN_DAO: any;
export declare const SCHEMA_RELATION_DAO: any;
export declare const SCHEMA_VERSION_DAO: any;
export declare const SCHEMA_VERSION_DMO: any;
