export declare const NPMJS_ORG___AIRPORT_TRAFFIC_PATTERN_QSCHEMA = "NPMJS_ORG___AIRPORT_TRAFFIC_PATTERN_QSCHEMA";
export declare const NPMJS_ORG___AIRPORT_TRAFFIC_PATTERN_DAOS: number;
export declare const NPMJS_ORG___AIRPORT_TRAFFIC_PATTERN_DMOS: number;
export declare const SCHEMA_COLUMN_DAO: number;
export declare const SCHEMA_DAO: number;
export declare const SCHEMA_ENTITY_DAO: number;
export declare const SCHEMA_PROPERTY_COLUMN_DAO: number;
export declare const SCHEMA_PROPERTY_DAO: number;
export declare const SCHEMA_REFERENCE_DAO: number;
export declare const SCHEMA_RELATION_COLUMN_DAO: number;
export declare const SCHEMA_RELATION_DAO: number;
export declare const SCHEMA_VERSION_DAO: number;
export declare const SCHEMA_VERSION_DMO: number;
