import { IDomainDao } from './dao/DomainDao';
import { ISchemaColumnDao } from './dao/SchemaColumnDao';
import { ISchemaDao } from './dao/SchemaDao';
import { ISchemaEntityDao } from './dao/SchemaEntityDao';
import { ISchemaPropertyColumnDao } from './dao/SchemaPropertyColumnDao';
import { ISchemaPropertyDao } from './dao/SchemaPropertyDao';
import { ISchemaReferenceDao } from './dao/SchemaReferenceDao';
import { ISchemaRelationColumnDao } from './dao/SchemaRelationColumnDao';
import { ISchemaRelationDao } from './dao/SchemaRelationDao';
import { ISchemaVersionDao } from './dao/SchemaVersionDao';
import { ISchemaVersionDuo } from './duo/SchemaVersionDuo';
export declare const DOMAIN_DAO: import("@airport/di").IDiToken<IDomainDao>;
export declare const SCHEMA_COLUMN_DAO: import("@airport/di").IDiToken<ISchemaColumnDao>;
export declare const SCHEMA_DAO: import("@airport/di").IDiToken<ISchemaDao>;
export declare const SCHEMA_ENTITY_DAO: import("@airport/di").IDiToken<ISchemaEntityDao>;
export declare const SCHEMA_PROPERTY_COLUMN_DAO: import("@airport/di").IDiToken<ISchemaPropertyColumnDao>;
export declare const SCHEMA_PROPERTY_DAO: import("@airport/di").IDiToken<ISchemaPropertyDao>;
export declare const SCHEMA_REFERENCE_DAO: import("@airport/di").IDiToken<ISchemaReferenceDao>;
export declare const SCHEMA_RELATION_COLUMN_DAO: import("@airport/di").IDiToken<ISchemaRelationColumnDao>;
export declare const SCHEMA_RELATION_DAO: import("@airport/di").IDiToken<ISchemaRelationDao>;
export declare const SCHEMA_VERSION_DAO: import("@airport/di").IDiToken<ISchemaVersionDao>;
export declare const SCHEMA_VERSION_DUO: import("@airport/di").IDiToken<ISchemaVersionDuo>;
//# sourceMappingURL=tokens.d.ts.map