import { NPMJS_ORG___AIRPORT_TRAFFIC_PATTERN_Daos } from './dao/dao';
import { ISchemaColumnDao } from './dao/SchemaColumnDao';
import { ISchemaDao } from './dao/SchemaDao';
import { ISchemaEntityDao } from './dao/SchemaEntityDao';
import { ISchemaPropertyColumnDao } from './dao/SchemaPropertyColumnDao';
import { ISchemaPropertyDao } from './dao/SchemaPropertyDao';
import { ISchemaReferenceDao } from './dao/SchemaReferenceDao';
import { ISchemaRelationColumnDao } from './dao/SchemaRelationColumnDao';
import { ISchemaRelationDao } from './dao/SchemaRelationDao';
import { ISchemaVersionDao } from './dao/SchemaVersionDao';
import { NPMJS_ORG___AIRPORT_TRAFFIC_PATTERN_Duos } from './duo/duo';
import { ISchemaVersionDuo } from './duo/SchemaVersionDuo';
export declare const NPMJS_ORG___AIRPORT_TRAFFIC_PATTERN_QSCHEMA = "NPMJS_ORG___AIRPORT_TRAFFIC_PATTERN_QSCHEMA";
export declare const NPMJS_ORG___AIRPORT_TRAFFIC_PATTERN_DAOS: import("@airport/di").IDiToken<NPMJS_ORG___AIRPORT_TRAFFIC_PATTERN_Daos>;
export declare const NPMJS_ORG___AIRPORT_TRAFFIC_PATTERN_DUOS: import("@airport/di").IDiToken<NPMJS_ORG___AIRPORT_TRAFFIC_PATTERN_Duos>;
export declare const SCHEMA_COLUMN_DAO: import("@airport/di").IDiToken<ISchemaColumnDao>;
export declare const SCHEMA_DAO: import("@airport/di").IDiToken<ISchemaDao>;
export declare const SCHEMA_ENTITY_DAO: import("@airport/di").IDiToken<ISchemaEntityDao>;
export declare const SCHEMA_PROPERTY_COLUMN_DAO: import("@airport/di").IDiToken<ISchemaPropertyColumnDao>;
export declare const SCHEMA_PROPERTY_DAO: import("@airport/di").IDiToken<ISchemaPropertyDao>;
export declare const SCHEMA_REFERENCE_DAO: import("@airport/di").IDiToken<ISchemaReferenceDao>;
export declare const SCHEMA_RELATION_COLUMN_DAO: import("@airport/di").IDiToken<ISchemaRelationColumnDao>;
export declare const SCHEMA_RELATION_DAO: import("@airport/di").IDiToken<ISchemaRelationDao>;
export declare const SCHEMA_VERSION_DAO: import("@airport/di").IDiToken<ISchemaVersionDao>;
export declare const SCHEMA_VERSION_DUO: import("@airport/di").IDiToken<ISchemaVersionDuo>;
