import { IDomainDao } from './dao/DomainDao';
import { IApplicationColumnDao } from './dao/ApplicationColumnDao';
import { IApplicationDao } from './dao/ApplicationDao';
import { IApplicationEntityDao } from './dao/ApplicationEntityDao';
import { IApplicationPropertyColumnDao } from './dao/ApplicationPropertyColumnDao';
import { IApplicationPropertyDao } from './dao/ApplicationPropertyDao';
import { IApplicationReferenceDao } from './dao/ApplicationReferenceDao';
import { IApplicationRelationColumnDao } from './dao/ApplicationRelationColumnDao';
import { IApplicationRelationDao } from './dao/ApplicationRelationDao';
import { IApplicationVersionDao } from './dao/ApplicationVersionDao';
import { IApplicationVersionDuo } from './duo/ApplicationVersionDuo';
export declare const DOMAIN_DAO: import("@airport/di").IDiToken<IDomainDao>;
export declare const APPLICATION_COLUMN_DAO: import("@airport/di").IDiToken<IApplicationColumnDao>;
export declare const APPLICATION_DAO: import("@airport/di").IDiToken<IApplicationDao>;
export declare const APPLICATION_ENTITY_DAO: import("@airport/di").IDiToken<IApplicationEntityDao>;
export declare const APPLICATION_PROPERTY_COLUMN_DAO: import("@airport/di").IDiToken<IApplicationPropertyColumnDao>;
export declare const APPLICATION_PROPERTY_DAO: import("@airport/di").IDiToken<IApplicationPropertyDao>;
export declare const APPLICATION_REFERENCE_DAO: import("@airport/di").IDiToken<IApplicationReferenceDao>;
export declare const APPLICATION_RELATION_COLUMN_DAO: import("@airport/di").IDiToken<IApplicationRelationColumnDao>;
export declare const APPLICATION_RELATION_DAO: import("@airport/di").IDiToken<IApplicationRelationDao>;
export declare const APPLICATION_VERSION_DAO: import("@airport/di").IDiToken<IApplicationVersionDao>;
export declare const APPLICATION_VERSION_DUO: import("@airport/di").IDiToken<IApplicationVersionDuo>;
//# sourceMappingURL=tokens.d.ts.map