import { ISynchronizationConflictDao } from "./dao/conflict/SynchronizationConflictDao";
import { ISynchronizationConflictPendingNotificationDao } from "./dao/conflict/SynchronizationConflictPendingNotificationDao";
import { ISynchronizationConflictValuesDao } from "./dao/conflict/SynchronizationConflictValuesDao";
import { IMissingRecordDao } from "./dao/missingRecord/MissingRecordDao";
import { IMissingRecordRepoTransBlockDao } from "./dao/missingRecord/MissingRecordRepoTransBlockDao";
import { IRecordUpdateStageDao } from "./dao/RecordUpdateStageDao";
import { IRepositoryTransactionBlockDao } from "./dao/repositoryTransactionBlock/RepositoryTransactionBlockDao";
import { IRepositoryTransactionHistoryUpdateStageDao } from "./dao/repositoryTransactionBlock/RepositoryTransactionHistoryUpdateStageDao";
import { IRepoTransBlockResponseStageDao } from "./dao/repositoryTransactionBlock/RepoTransBlockResponseStageDao";
import { IRepoTransBlockSchemaToChangeDao } from "./dao/repositoryTransactionBlock/RepoTransBlockSchemaToChangeDao";
import { ISharingMessageDao } from "./dao/sharingMessage/SharingMessageDao";
import { ISharingMessageRepoTransBlockDao } from "./dao/sharingMessage/SharingMessageRepoTransBlockDao";
import { ISharingNodeDao } from "./dao/sharingNode/SharingNodeDao";
import { ISharingNodeTerminalDao } from "./dao/sharingNode/SharingNodeTerminalDao";
import { ISharingNodeRepositoryDao } from "./dao/sharingNode/SharingNodeRepositoryDao";
import { ISharingNodeRepoTransBlockDao } from "./dao/sharingNode/SharingNodeRepoTransBlockDao";
import { ISharingNodeRepoTransBlockStageDao } from "./dao/sharingNode/SharingNodeRepoTransBlockStageDao";
import { IRepositoryTransactionBlockDmo } from "./dmo/repositoryTransactionBlock/RepositoryTransactionBlockDmo";
export declare const MISSING_RECORD_DAO: import("@airport/di").DiToken<IMissingRecordDao>;
export declare const MISSING_RECORD_REPO_TRANS_BLOCK_DAO: import("@airport/di").DiToken<IMissingRecordRepoTransBlockDao>;
export declare const RECORD_UPDATE_STAGE_DAO: import("@airport/di").DiToken<IRecordUpdateStageDao>;
export declare const REPO_TRANS_BLOCK_DAO: import("@airport/di").DiToken<IRepositoryTransactionBlockDao>;
export declare const REPO_TRANS_BLOCK_DMO: import("@airport/di").DiToken<IRepositoryTransactionBlockDmo>;
export declare const REPO_TRANS_HISTORY_UPDATE_STAGE_DAO: import("@airport/di").DiToken<IRepositoryTransactionHistoryUpdateStageDao>;
export declare const REPO_TRANS_BLOCK_RESPONSE_STAGE_DAO: import("@airport/di").DiToken<IRepoTransBlockResponseStageDao>;
export declare const SHARING_MESSAGE_DAO: import("@airport/di").DiToken<ISharingMessageDao>;
export declare const SHARING_MESSAGE_REPO_TRANS_BLOCK_DAO: import("@airport/di").DiToken<ISharingMessageRepoTransBlockDao>;
export declare const REPO_TRANS_BLOCK_SCHEMA_TO_CHANGE_DAO: import("@airport/di").DiToken<IRepoTransBlockSchemaToChangeDao>;
export declare const SHARING_NODE_DAO: import("@airport/di").DiToken<ISharingNodeDao>;
export declare const SHARING_NODE_TERMINAL_DAO: import("@airport/di").DiToken<ISharingNodeTerminalDao>;
export declare const SHARING_NODE_REPOSITORY_DAO: import("@airport/di").DiToken<ISharingNodeRepositoryDao>;
export declare const SHARING_NODE_REPO_TRANS_BLOCK_DAO: import("@airport/di").DiToken<ISharingNodeRepoTransBlockDao>;
export declare const SHARING_NODE_REPO_TRANS_BLOCK_STAGE_DAO: import("@airport/di").DiToken<ISharingNodeRepoTransBlockStageDao>;
export declare const SYNC_CONFLICT_DAO: import("@airport/di").DiToken<ISynchronizationConflictDao>;
export declare const SYNC_CONFLICT_PENDING_NOTIFICATION_DAO: import("@airport/di").DiToken<ISynchronizationConflictPendingNotificationDao>;
export declare const SYNC_CONFLICT_VALUES_DAO: import("@airport/di").DiToken<ISynchronizationConflictValuesDao>;
