import { Token } from "typedi/Token";
import { ISynchronizationConflictDao } from "./dao/conflict/SynchronizationConflictDao";
import { ISynchronizationConflictPendingNotificationDao } from "./dao/conflict/SynchronizationConflictPendingNotificationDao";
import { ISynchronizationConflictValuesDao } from "./dao/conflict/SynchronizationConflictValuesDao";
import { IMissingRecordDao } from "./dao/missingRecord/MissingRecordDao";
import { IMissingRecordRepoTransBlockDao } from "./dao/missingRecord/MissingRecordRepoTransBlockDao";
import { IRecordUpdateStageDao } from "./dao/RecordUpdateStageDao";
import { IRepositoryTransactionBlockDao } from "./dao/repositoryTransactionBlock/RepositoryTransactionBlockDao";
import { IRepositoryTransactionHistoryUpdateStageDao } from "./dao/repositoryTransactionBlock/RepositoryTransactionHistoryUpdateStageDao";
import { IRepoTransBlockResponseStageDao } from "./dao/repositoryTransactionBlock/RepoTransBlockResponseStageDao";
import { IRepoTransBlockSchemasToChangeDao } from "./dao/repositoryTransactionBlock/RepoTransBlockSchemasToChangeDao";
import { ISharingMessageDao } from "./dao/sharingMessage/SharingMessageDao";
import { ISharingMessageRepoTransBlockDao } from "./dao/sharingMessage/SharingMessageRepoTransBlockDao";
import { ISharingNodeDao } from "./dao/sharingNode/SharingNodeDao";
import { ISharingNodeTerminalDao } from "./dao/sharingNode/SharingNodeTerminalDao";
import { ISharingNodeRepositoryDao } from "./dao/sharingNode/SharingNodeRepositoryDao";
import { ISharingNodeRepoTransBlockDao } from "./dao/sharingNode/SharingNodeRepoTransBlockDao";
import { ISharingNodeRepoTransBlockStageDao } from "./dao/sharingNode/SharingNodeRepoTransBlockStageDao";
import { IRepositoryTransactionBlockDmo } from "./dmo/repositoryTransactionBlock/RepositoryTransactionBlockDmo";
export declare const MissingRecordDaoToken: Token<IMissingRecordDao>;
export declare const MissingRecordRepoTransBlockDaoToken: Token<IMissingRecordRepoTransBlockDao>;
export declare const RecordUpdateStageDaoToken: Token<IRecordUpdateStageDao>;
export declare const RepositoryTransactionBlockDaoToken: Token<IRepositoryTransactionBlockDao>;
export declare const RepositoryTransactionBlockDmoToken: Token<IRepositoryTransactionBlockDmo>;
export declare const RepositoryTransactionHistoryUpdateStageDaoToken: Token<IRepositoryTransactionHistoryUpdateStageDao>;
export declare const RepoTransBlockResponseStageDaoToken: Token<IRepoTransBlockResponseStageDao>;
export declare const SharingMessageDaoToken: Token<ISharingMessageDao>;
export declare const SharingMessageRepoTransBlockDaoToken: Token<ISharingMessageRepoTransBlockDao>;
export declare const RepoTransBlockSchemasToChangeDaoToken: Token<IRepoTransBlockSchemasToChangeDao>;
export declare const SharingNodeDaoToken: Token<ISharingNodeDao>;
export declare const SharingNodeTerminalDaoToken: Token<ISharingNodeTerminalDao>;
export declare const SharingNodeRepositoryDaoToken: Token<ISharingNodeRepositoryDao>;
export declare const SharingNodeRepoTransBlockDaoToken: Token<ISharingNodeRepoTransBlockDao>;
export declare const SharingNodeRepoTransBlockStageDaoToken: Token<ISharingNodeRepoTransBlockStageDao>;
export declare const SynchronizationConflictDaoToken: Token<ISynchronizationConflictDao>;
export declare const SynchronizationConflictPendingNotificationDaoToken: Token<ISynchronizationConflictPendingNotificationDao>;
export declare const SynchronizationConflictValuesDaoToken: Token<ISynchronizationConflictValuesDao>;
