import { ISynchronizationConflictDao } from "./dao/conflict/SynchronizationConflictDao";
import { ISynchronizationConflictPendingNotificationDao } from "./dao/conflict/SynchronizationConflictPendingNotificationDao";
import { ISynchronizationConflictValuesDao } from "./dao/conflict/SynchronizationConflictValuesDao";
import { IMissingRecordDao } from "./dao/missingRecord/MissingRecordDao";
import { IMissingRecordRepoTransBlockDao } from "./dao/missingRecord/MissingRecordRepoTransBlockDao";
import { IRecordUpdateStageDao } from "./dao/RecordUpdateStageDao";
import { IRepositoryTransactionBlockDao } from "./dao/repositoryTransactionBlock/RepositoryTransactionBlockDao";
import { IRepositoryTransactionHistoryUpdateStageDao } from "./dao/repositoryTransactionBlock/RepositoryTransactionHistoryUpdateStageDao";
import { IRepoTransBlockResponseStageDao } from "./dao/repositoryTransactionBlock/RepoTransBlockResponseStageDao";
import { IRepoTransBlockSchemaToChangeDao } from "./dao/repositoryTransactionBlock/RepoTransBlockSchemaToChangeDao";
import { ISharingMessageDao } from "./dao/sharingMessage/SharingMessageDao";
import { ISharingMessageRepoTransBlockDao } from "./dao/sharingMessage/SharingMessageRepoTransBlockDao";
import { ISharingNodeDao } from "./dao/sharingNode/SharingNodeDao";
import { ISharingNodeTerminalDao } from "./dao/sharingNode/SharingNodeTerminalDao";
import { ISharingNodeRepositoryDao } from "./dao/sharingNode/SharingNodeRepositoryDao";
import { ISharingNodeRepoTransBlockDao } from "./dao/sharingNode/SharingNodeRepoTransBlockDao";
import { ISharingNodeRepoTransBlockStageDao } from "./dao/sharingNode/SharingNodeRepoTransBlockStageDao";
import { IRepositoryTransactionBlockDuo } from "./duo/repositoryTransactionBlock/RepositoryTransactionBlockDuo";
export declare const MISSING_RECORD_DAO: import("@airport/di").IDiToken<IMissingRecordDao>;
export declare const MISSING_RECORD_REPO_TRANS_BLOCK_DAO: import("@airport/di").IDiToken<IMissingRecordRepoTransBlockDao>;
export declare const RECORD_UPDATE_STAGE_DAO: import("@airport/di").IDiToken<IRecordUpdateStageDao>;
export declare const REPO_TRANS_BLOCK_DAO: import("@airport/di").IDiToken<IRepositoryTransactionBlockDao>;
export declare const REPO_TRANS_BLOCK_DUO: import("@airport/di").IDiToken<IRepositoryTransactionBlockDuo>;
export declare const REPO_TRANS_HISTORY_UPDATE_STAGE_DAO: import("@airport/di").IDiToken<IRepositoryTransactionHistoryUpdateStageDao>;
export declare const REPO_TRANS_BLOCK_RESPONSE_STAGE_DAO: import("@airport/di").IDiToken<IRepoTransBlockResponseStageDao>;
export declare const SHARING_MESSAGE_DAO: import("@airport/di").IDiToken<ISharingMessageDao>;
export declare const SHARING_MESSAGE_REPO_TRANS_BLOCK_DAO: import("@airport/di").IDiToken<ISharingMessageRepoTransBlockDao>;
export declare const REPO_TRANS_BLOCK_SCHEMA_TO_CHANGE_DAO: import("@airport/di").IDiToken<IRepoTransBlockSchemaToChangeDao>;
export declare const SHARING_NODE_DAO: import("@airport/di").IDiToken<ISharingNodeDao>;
export declare const SHARING_NODE_TERMINAL_DAO: import("@airport/di").IDiToken<ISharingNodeTerminalDao>;
export declare const SHARING_NODE_REPOSITORY_DAO: import("@airport/di").IDiToken<ISharingNodeRepositoryDao>;
export declare const SHARING_NODE_REPO_TRANS_BLOCK_DAO: import("@airport/di").IDiToken<ISharingNodeRepoTransBlockDao>;
export declare const SHARING_NODE_REPO_TRANS_BLOCK_STAGE_DAO: import("@airport/di").IDiToken<ISharingNodeRepoTransBlockStageDao>;
export declare const SYNC_CONFLICT_DAO: import("@airport/di").IDiToken<ISynchronizationConflictDao>;
export declare const SYNC_CONFLICT_PENDING_NOTIFICATION_DAO: import("@airport/di").IDiToken<ISynchronizationConflictPendingNotificationDao>;
export declare const SYNC_CONFLICT_VALUES_DAO: import("@airport/di").IDiToken<ISynchronizationConflictValuesDao>;
//# sourceMappingURL=tokens.d.ts.map