export declare enum BlockSyncStatus {
    SYNCHRONIZING = "SYNCHRONIZING",
    SYNCHRONIZED = "SYNCHRONIZED",
    REQUESTING_SYNC_STATUS = "REQUESTING_SYNC_STATUS",
    RESYNC_REQUESTED = "RESYNC_REQUESTED"
}
export declare enum RepositorySyncStatus {
    ACTIVE = "ACTIVE",
    PENDING = "PENDING",
    DELAYED = "DELAYED",
    SUSPENDED = "SUSPENDED",
    TEMPORARILY_REROUTED = "TEMPORARILY_REROUTED",
    PERMANENTLY_REROUTED = "PERMANENTLY_REROUTED"
}
export declare enum TerminalSyncStatus {
    ACTIVE = "ACTIVE",
    SUSPENDED = "SUSPENDED"
}
//# sourceMappingURL=SyncStatus.d.ts.map