export declare type TmToAgtProtocolVersion = 0;
export declare enum MessageToTMContentType {
    REPOSITORY_TRANSACTION_BLOCK = 0,
    SYNC_NOTIFICATION = 1,
    ALIVE_ACK = 2
}
export declare enum RepoTransBlockSyncOutcomeType {
    BLOCK_IS_LOCAL = 0,
    SYNC_TO_TM_SUCCESSFUL = 1,
    SYNC_TO_TM_READY_FOR_PROCESSING = 2,
    SYNC_TO_TM_NEEDS_SCHEMA_CHANGES = 3,
    SYNC_TO_TM_NEEDS_ADDITIONAL_DATA = 4,
    SYNC_TO_TM_INVALID_DATA = 5,
    SYNC_TO_TM_NEEDS_DATA_UPGRADES = 6
}
export declare enum SharingNodeRepoTransBlockSyncStatus {
    TM_STATUS_RTB_SYNCHRONIZING = 0,
    TM_STATUS_REQUESTING_RTB_SYNC_STATUS = 1,
    TM_STATUS_RTB_RESYNC_REQUESTED = 2,
    AGT_STATUS_RTB_ALREADY_SYNCED = 3,
    AGT_STATUS_RTB_SYNC_SUCCESSFUL = 4,
    AGT_STATUS_RTB_SYNC_DENIED_DATABASE_NOT_FOUND = 5,
    AGT_STATUS_RTB_SYNC_DENIED_REPOSITORY_NOT_FOUND = 6,
    AGT_STATUS_RTB_SYNC_DENIED_NO_WRITE_PERMISSION = 7
}
export declare enum MessageFromTMContentType {
    CONNECTION_REQUEST = 0,
    SYNC_VERIFICATIONS = 1,
    DATA_TRANSFER = 2
}
