import {
    and, not, or,
    bool, date, num, str, wrapPrimitive,
    abs, add, avg, concat, count, distinct, divide, exists,
    format, intersect, lcase, len, max, mid, min, minus,
    modulus, multiply, now, replace, round, subtract, sum,
    trim, ucase, union, unionAll
} from "@airport/tarmaq-query";
import { IDatabaseState } from "../definition/DatabaseState";

export const databaseState: IDatabaseState = {
    applications: [],
    entityMap: new Map(),
    functions: {
        abs,
        avg,
        count,
        max,
        min,
        sum,
        ucase,
        lcase,
        mid,
        len,
        round,
        now,
        format,
        replace,
        trim,
        distinct,
        exists,
        divide,
        subtract,
        modulus,
        multiply,
        add,
        concat,
        union,
        unionAll,
        intersect,
        minus,
        // logical operators
        and,
        not,
        or,
        // primitive wrappers
        bool,
        date,
        num,
        str,
        wrapPrimitive,
    },
    qApplications: [],
    QM: {},
}