import {
    AND, NOT, OR,
    bool, date, num, str, wrapPrimitive,
    ABS, ADD, AVG, CONCAT, COUNT, DISTINCT, DIVIDE, EXISTS,
    FORMAT, INTERSECT, LCASE, LEN, MAX, MID, MIN, MINUS,
    MODULUS, MULTIPLY, NOW, REPLACE, ROUND, SUBTRACT, SUM,
    TRIM, UCASE, UNION, UNION_ALL
} from "@airport/tarmaq-query";
import { IDatabaseState } from "../definition/IDatabaseState";

export const databaseState: IDatabaseState = {
    applications: [],
    entityMap: new Map(),
    functions: {
        ABS,
        ADD,
        AVG,
        CONCAT,
        COUNT,
        DISTINCT,
        DIVIDE,
        EXISTS,
        FORMAT,
        INTERSECT,
        LCASE,
        LEN,
        ROUND,
        MAX,
        MID,
        MIN,
        MINUS,
        MODULUS,
        MULTIPLY,
        NOW,
        REPLACE,
        SUBTRACT,
        SUM,
        TRIM,
        UCASE,
        UNION,
        UNION_ALL,
        // logical operators
        AND,
        NOT,
        OR,
        // primitive wrappers
        bool,
        date,
        num,
        str,
        wrapPrimitive,
    },
    qApplications: [],
    QM: {},
}