import { IRecordHistoryNewValueDao } from './dao/history/RecordHistoryNewValueDao';
import { IRecordHistoryOldValueDao } from './dao/history/RecordHistoryOldValueDao';
import { IRepositoryTransactionHistoryDao } from './dao/history/RepositoryTransactionHistoryDao';
import { IActorDao } from './dao/infrastructure/ActorDao';
import { IRepositoryActorDao } from './dao/repository/RepositoryActorDao';
import { IRepositoryDao } from './dao/repository/RepositoryDao';
import { IOperationHistoryDmo } from './dmo/history/OperationHistoryDmo';
import { IRecordHistoryDmo } from './dmo/history/RecordHistoryDmo';
import { IRecordHistoryNewValueDmo } from './dmo/history/RecordHistoryNewValueDmo';
import { IRecordHistoryOldValueDmo } from './dmo/history/RecordHistoryOldValueDmo';
import { IRepositoryTransactionHistoryDmo } from './dmo/history/RepositoryTransactionHistoryDmo';
import { ITransactionHistoryDmo } from './dmo/history/TransactionHistoryDmo';
export declare const ACTOR_DAO: import("@airport/di").DiToken<IActorDao>;
export declare const OPERATION_HISTORY_DMO: import("@airport/di").DiToken<IOperationHistoryDmo>;
export declare const RECORD_HISTORY_DMO: import("@airport/di").DiToken<IRecordHistoryDmo>;
export declare const RECORD_HISTORY_NEW_VALUE_DAO: import("@airport/di").DiToken<IRecordHistoryNewValueDao>;
export declare const RECORD_HISTORY_NEW_VALUE_DMO: import("@airport/di").DiToken<IRecordHistoryNewValueDmo>;
export declare const RECORD_HISTORY_OLD_VALUE_DAO: import("@airport/di").DiToken<IRecordHistoryOldValueDao>;
export declare const RECORD_HISTORY_OLD_VALUE_DMO: import("@airport/di").DiToken<IRecordHistoryOldValueDmo>;
export declare const REPOSITORY_ACTOR_DAO: import("@airport/di").DiToken<IRepositoryActorDao>;
export declare const REPOSITORY_DAO: import("@airport/di").DiToken<IRepositoryDao>;
export declare const REPOSITORY_TRANSACTION_HISTORY_DAO: import("@airport/di").DiToken<IRepositoryTransactionHistoryDao>;
export declare const REPOSITORY_TRANSACTION_HISTORY_DMO: import("@airport/di").DiToken<IRepositoryTransactionHistoryDmo>;
export declare const TRANSACTION_HISTORY_DMO: import("@airport/di").DiToken<ITransactionHistoryDmo>;
