import { Token } from "typedi";
import { IRecordHistoryNewValueDao } from "./dao/history/RecordHistoryNewValueDao";
import { IRecordHistoryOldValueDao } from "./dao/history/RecordHistoryOldValueDao";
import { IRepositoryTransactionHistoryDao } from "./dao/history/RepositoryTransactionHistoryDao";
import { IActorDao } from "./dao/infrastructure/ActorDao";
import { IDatabaseDao } from "./dao/infrastructure/DatabaseDao";
import { IUserDao } from "./dao/infrastructure/UserDao";
import { IRepositoryActorDao } from "./dao/repository/RepositoryActorDao";
import { IRepositoryDao } from "./dao/repository/RepositoryDao";
import { IOperationHistoryDmo } from "./dmo/history/OperationHistoryDmo";
import { IRecordHistoryDmo } from "./dmo/history/RecordHistoryDmo";
import { IRecordHistoryNewValueDmo } from "./dmo/history/RecordHistoryNewValueDmo";
import { IRecordHistoryOldValueDmo } from "./dmo/history/RecordHistoryOldValueDmo";
import { IRepositoryTransactionHistoryDmo } from "./dmo/history/RepositoryTransactionHistoryDmo";
import { ITransactionHistoryDmo } from "./dmo/history/TransactionHistoryDmo";
export declare const ActorDaoToken: Token<IActorDao>;
export declare const DatabaseDaoToken: Token<IDatabaseDao>;
export declare const OperationHistoryDmoToken: Token<IOperationHistoryDmo>;
export declare const RecordHistoryDmoToken: Token<IRecordHistoryDmo>;
export declare const RecordHistoryNewValueDaoToken: Token<IRecordHistoryNewValueDao>;
export declare const RecordHistoryNewValueDmoToken: Token<IRecordHistoryNewValueDmo>;
export declare const RecordHistoryOldValueDaoToken: Token<IRecordHistoryOldValueDao>;
export declare const RecordHistoryOldValueDmoToken: Token<IRecordHistoryOldValueDmo>;
export declare const RepositoryActorDaoToken: Token<IRepositoryActorDao>;
export declare const RepositoryDaoToken: Token<IRepositoryDao>;
export declare const RepositoryTransactionHistoryDaoToken: Token<IRepositoryTransactionHistoryDao>;
export declare const RepositoryTransactionHistoryDmoToken: Token<IRepositoryTransactionHistoryDmo>;
export declare const TransactionHistoryDmoToken: Token<ITransactionHistoryDmo>;
export declare const UserDaoToken: Token<IUserDao>;
