import { ICascadeGraphVerifier, IDatabaseManager, IDeleteManager, IDependencyGraphResolver, IEntityGraphReconstructor, IHistoryManager, IInsertManager, IOperationManager, IQueryManager, IRepositoryManager, IStructuralEntityValidator, IUpdateManager } from '@airport/terminal-map';
import { IInternalRecordManager } from './data/InternalRecordManager';
import { IOnlineManager } from './net/OnlineManager';
import { TransactionalReceiver } from './net/TransactionalReceiver';
import { AbstractMutationManager } from './orchestration/AbstractMutationManager';
export declare const ABSTRACT_MUTATION_MANAGER: import("@airport/direction-indicator").IDependencyInjectionToken<AbstractMutationManager>;
export declare const ABSTRACT_TRANSACTIONAL_RECEIVER: import("@airport/direction-indicator").IDependencyInjectionToken<TransactionalReceiver>;
export declare const CASCADE_GRAPH_VERIFIER: import("@airport/direction-indicator").IDependencyInjectionToken<ICascadeGraphVerifier>;
export declare const DATABASE_MANAGER: import("@airport/direction-indicator").IDependencyInjectionToken<IDatabaseManager>;
export declare const DELETE_MANAGER: import("@airport/direction-indicator").IDependencyInjectionToken<IDeleteManager>;
export declare const DEPENDENCY_GRAPH_RESOLVER: import("@airport/direction-indicator").IDependencyInjectionToken<IDependencyGraphResolver>;
export declare const ENTITY_GRAPH_RECONSTRUCTOR: import("@airport/direction-indicator").IDependencyInjectionToken<IEntityGraphReconstructor>;
export declare const HISTORY_MANAGER: import("@airport/direction-indicator").IDependencyInjectionToken<IHistoryManager>;
export declare const INSERT_MANAGER: import("@airport/direction-indicator").IDependencyInjectionToken<IInsertManager>;
export declare const INTERNAL_RECORD_MANAGER: import("@airport/direction-indicator").IDependencyInjectionToken<IInternalRecordManager>;
export declare const ONLINE_MANAGER: import("@airport/direction-indicator").IDependencyInjectionToken<IOnlineManager>;
export declare const OPERATION_MANAGER: import("@airport/direction-indicator").IDependencyInjectionToken<IOperationManager>;
export declare const QUERY_MANAGER: import("@airport/direction-indicator").IDependencyInjectionToken<IQueryManager>;
export declare const REPOSITORY_MANAGER: import("@airport/direction-indicator").IDependencyInjectionToken<IRepositoryManager>;
export declare const STRUCTURAL_ENTITY_VALIDATOR: import("@airport/direction-indicator").IDependencyInjectionToken<IStructuralEntityValidator>;
export declare const UPDATE_MANAGER: import("@airport/direction-indicator").IDependencyInjectionToken<IUpdateManager>;
//# sourceMappingURL=tokens.d.ts.map